const CITY_MAP: Record<string, string> = {
  'амстердам': 'Amsterdam',
  'барселона': 'Barcelona',
  'лісабон': 'Lisbon',
  'лиссабон': 'Lisbon',
  'париж': 'Paris',
  'лондон': 'London',
  'берлін': 'Berlin',
  'берлин': 'Berlin',
  'прага': 'Prague',
  'рим': 'Rome',
  'мадрид': 'Madrid',
  'краків': 'Krakow',
  'краков': 'Krakow',
  'відень': 'Vienna',
  'вена': 'Vienna',
  'будапешт': 'Budapest',
  'стамбул': 'Istanbul',
  'варшава': 'Warsaw',
  'мілан': 'Milan',
  'милан': 'Milan',
  'флоренція': 'Florence',
  'флоренция': 'Florence',
  'венеція': 'Venice',
  'венеция': 'Venice',
  'неаполь': 'Naples',
  'афіни': 'Athens',
  'афины': 'Athens',
  'копенгаген': 'Copenhagen',
  'стокгольм': 'Stockholm',
  'осло': 'Oslo',
  'хельсінкі': 'Helsinki',
  'хельсинки': 'Helsinki',
  'таллінн': 'Tallinn',
  'таллин': 'Tallinn',
  'рига': 'Riga',
  'вільнюс': 'Vilnius',
  'вильнюс': 'Vilnius',
  'брюссель': 'Brussels',
  'женева': 'Geneva',
  'цюріх': 'Zurich',
  'цюрих': 'Zurich',
  'мюнхен': 'Munich',
  'франкфурт': 'Frankfurt',
  'гамбург': 'Hamburg',
  'дюссельдорф': 'Dusseldorf',
  'дюсельдорф': 'Dusseldorf',
  'кельн': 'Cologne',
  'дублін': 'Dublin',
  'дублин': 'Dublin',
  'едінбург': 'Edinburgh',
  'эдинбург': 'Edinburgh',
  'порто': 'Porto',
  'порту': 'Porto',
  'севілья': 'Seville',
  'севилья': 'Seville',
  'валенсія': 'Valencia',
  'валенсия': 'Valencia',
  'малага': 'Malaga',
  'пальма': 'Palma de Mallorca',
  'ібіца': 'Ibiza',
  'ибица': 'Ibiza',
  'ніцца': 'Nice',
  'ницца': 'Nice',
  'марсель': 'Marseille',
  'лион': 'Lyon',
  'ліон': 'Lyon',
  'бордо': 'Bordeaux',
  'львів': 'Lviv',
  'львов': 'Lviv',
  'київ': 'Kyiv',
  'киев': 'Kyiv',
  'одеса': 'Odesa',
  'одесса': 'Odesa',
  'тбілісі': 'Tbilisi',
  'тбилиси': 'Tbilisi',
  'батумі': 'Batumi',
  'батуми': 'Batumi',
  'єреван': 'Yerevan',
  'ереван': 'Yerevan',
  'дубай': 'Dubai',
  'нью-йорк': 'New York',
  'лос-анджелес': 'Los Angeles',
  'сан-франциско': 'San Francisco',
  'майамі': 'Miami',
  'майами': 'Miami',
  'токіо': 'Tokyo',
  'токио': 'Tokyo',
  'бангкок': 'Bangkok',
  'пхукет': 'Phuket',
  'балі': 'Bali',
  'бали': 'Bali',
};

export function normalizeDestination(input: string): string {
  const trimmed = input.trim();
  if (!trimmed) return trimmed;
  const key = trimmed.toLowerCase();
  const mapped = CITY_MAP[key];
  if (mapped) return mapped;
  if (!/[\u0400-\u04FF]/.test(trimmed)) return trimmed;
  for (const [ru, en] of Object.entries(CITY_MAP)) {
    if (key.includes(ru)) return en;
  }
  return trimmed;
}
